@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "1awdawd"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "user",
  "email": "user1@email.com",
  "password": "123456"
}
