@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.acessToken}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "joao@gmail.com",
  "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@gmail.com",
  "password": "123456"
}

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "João",
  "email": "joao@gmail.com"
}

### Update User Password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "1234567",
  "newPassword": "123456"
}

### Read One User
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete One User
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

